# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Windows Release Build

on:
 push:
    tags:
      - 'v*.*.*'  # Only run on version tags, e.g., v1.0.0
 workflow_dispatch:

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ChaosGroove/ChaosGroove.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Create ZIP with EXE + DLLs
      run: |
        mkdir release
        copy ChaosGroove\bin\Release\*.exe release\
        copy ChaosGroove\bin\Release\*.dll release\
        copy ChaosGroove\raylib\lib\*.dll release\
        copy ChaosGroove\create_shortcut.bat release\
        copy ChaosGroove\Gfx release\
        copy ChaosGroove\Music release\
        copy ChaosGroove\Pieces release\
        copy ChaosGroove\Shaders release\
        copy ChaosGroove\Sounds release\
        copy ChaosGroove\Spells release\
        copy ChaosGroove\Text_Files release\
        powershell Compress-Archive -Path release\* -DestinationPath build-release.zip
    
    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-release
        path: build-release.zip
